<a href="https://colab.research.google.com/github/nur21horin/pyscript/blob/main/TensorFLowLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_gpu_available())

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


2.20.0
False


In [3]:
import tensorflow as tf
x=tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
a=tf.constant(10)
b=tf.constant(39)
print(a+b)

tf.Tensor(49, shape=(), dtype=int32)


In [9]:
matrix=tf.constant([
    [1,2,4],
    [3,4,5],
    [5,6,4]
])
print(matrix)

tf.Tensor(
[[1 2 4]
 [3 4 5]
 [5 6 4]], shape=(3, 3), dtype=int32)


In [10]:
print(matrix.shape)

(3, 3)


In [11]:
w=tf.Variable(5)
w.assign(10)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [12]:
import numpy as np
import tensorflow as tf
arr=np.array([1,2,3])
tensor=tf.convert_to_tensor(arr)
print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
