<a href="https://colab.research.google.com/github/nur21horin/pyscript/blob/main/TensorFLowLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_gpu_available())

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


2.20.0
False


In [3]:
import tensorflow as tf
x=tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
a=tf.constant(10)
b=tf.constant(39)
print(a+b)

tf.Tensor(49, shape=(), dtype=int32)


In [9]:
matrix=tf.constant([
    [1,2,4],
    [3,4,5],
    [5,6,4]
])
print(matrix)

tf.Tensor(
[[1 2 4]
 [3 4 5]
 [5 6 4]], shape=(3, 3), dtype=int32)


In [10]:
print(matrix.shape)

(3, 3)


In [11]:
w=tf.Variable(5)
w.assign(10)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [12]:
import numpy as np
import tensorflow as tf
arr=np.array([1,2,3])
tensor=tf.convert_to_tensor(arr)
print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [14]:
from tensorflow import keras
from tensorflow.keras import layers

In [15]:
model = keras.Sequential([
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [18]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

To train your model, you need to provide data. I'll load the MNIST dataset, which is a common dataset for image classification, and prepare it for training. This includes normalizing the pixel values and flattening the images for the `Dense` layers.

In [21]:
import numpy as np

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Normalize pixel values to be between 0 and 1
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Flatten the images for a dense layer network
x_train = x_train.reshape(-1, 28 * 28)
x_test = x_test.reshape(-1, 28 * 28)

print(f"Shape of x_train: {x_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of x_test: {x_test.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of x_train: (60000, 784)
Shape of y_train: (60000,)
Shape of x_test: (10000, 784)
Shape of y_test: (10000,)


In [22]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9163 - loss: 0.2974
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9595 - loss: 0.1431
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9694 - loss: 0.1039
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9753 - loss: 0.0815
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9793 - loss: 0.0667
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9832 - loss: 0.0550
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9855 - loss: 0.0465
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9873 - loss: 0.0401
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9899 - loss: 0.0338
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9909 - loss: 0.0293


In [23]:
model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9755 - loss: 0.0875


[0.08750327676534653, 0.9754999876022339]

In [25]:
prediction=model.predict(x_test)
print(prediction)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
[[3.12033066e-09 3.62498559e-10 1.72243672e-05 ... 9.99965966e-01
  1.49820096e-07 1.15925786e-07]
 [1.81307724e-09 4.66910606e-05 9.99952614e-01 ... 2.16708784e-19
  1.77556757e-07 2.28587670e-16]
 [1.14353625e-07 9.98374820e-01 1.48103345e-05 ... 3.08002112e-04
  1.21078955e-03 2.63341917e-06]
 ...
 [1.55195190e-16 8.63086816e-16 3.09713388e-16 ... 1.18781472e-07
  1.72501458e-09 8.77702675e-08]
 [1.16140839e-08 4.41047285e-12 6.54195881e-12 ... 5.88155011e-11
  2.34383537e-04 1.38433956e-13]
 [1.49958490e-09 9.53248175e-11 2.36040250e-07 ... 2.17082971e-12
  2.38055600e-11 1.77093149e-12]]


In [26]:
print(tf.config.list_physical_devices('GPU'))

[]
